"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";

type Settings = { site_name: string; site_subtitle: string; studio_image: string | null; contact_wechat: string | null; contact_qq: string | null; contact_phone: string | null; contact_description: string | null };
const empty: Settings = { site_name: "", site_subtitle: "", studio_image: null, contact_wechat: "", contact_qq: "", contact_phone: "", contact_description: "" };
export default function AdminSettings() {
  const [settings, setSettings] = useState(empty); const [preview, setPreview] = useState<string | null>(null); const [image, setImage] = useState<File | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/settings").then((response) => response.json()).then(setSettings); }, []);
  const update = (key: keyof Settings, value: string | null) => setSettings((current) => ({ ...current, [key]: value }));
  const chooseImage = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) { setImage(file); setPreview(URL.createObjectURL(file)); } };
  const save = async (event: FormEvent) => { event.preventDefault(); setMessage("保存中..."); let next = settings; if (image) { const body = new FormData(); body.append("file", image); const upload = await fetch("/api/admin/uploads/studio-image", { method: "POST", body }); if (!upload.ok) { setMessage("图片上传失败"); return; } next = { ...settings, studio_image: (await upload.json()).path }; } const response = await fetch("/api/admin/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(next) }); if (response.ok) { setSettings(await response.json()); setImage(null); setMessage("已保存"); } else setMessage("保存失败"); };
  return <main className="admin-shell"><nav className="admin-nav"><strong>11号电竞后台</strong><a href="/admin">概览</a><a href="/admin/games">游戏管理</a><a href="/admin/settings">网站设置</a></nav><section className="dashboard"><p className="eyebrow">SETTINGS</p><h1>网站设置</h1><form className="settings-form" onSubmit={save}><label>网站名称<input value={settings.site_name} onChange={(event) => update("site_name", event.target.value)} required /></label><label>副标题<input value={settings.site_subtitle} onChange={(event) => update("site_subtitle", event.target.value)} required /></label><label>微信号<input value={settings.contact_wechat ?? ""} onChange={(event) => update("contact_wechat", event.target.value)} /></label><label>QQ 号<input value={settings.contact_qq ?? ""} onChange={(event) => update("contact_qq", event.target.value)} /></label><label>电话<input value={settings.contact_phone ?? ""} onChange={(event) => update("contact_phone", event.target.value)} /></label><label>咨询提示<textarea value={settings.contact_description ?? ""} onChange={(event) => update("contact_description", event.target.value)} /></label><label>工作室图片<input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage} />{(preview || settings.studio_image) && <img className="settings-preview" src={preview || settings.studio_image || ""} alt="工作室预览" />}</label><div><button className="admin-action" type="submit">保存设置</button><span className="save-message">{message}</span></div></form></section></main>;
}
