"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { AdminLayout, AdminPageTitle } from "../../../../components/admin-layout";

type Service = { id: number; name: string; price: string; description: string; sort_order: number; is_active: boolean };
type Game = { id: number; name: string; slug: string; tag: string; description: string; cover_image: string; accent_color: string; accent_color_2: string; sort_order: number; is_active: boolean; services: Service[] };
const emptyService = { name: "", price: "", description: "", sort_order: 0, is_active: true };
const payload = (game: Game) => ({ name: game.name, slug: game.slug, tag: game.tag, description: game.description, cover_image: game.cover_image, accent_color: game.accent_color, accent_color_2: game.accent_color_2, sort_order: game.sort_order, is_active: game.is_active });
export default function EditGame() {
  const { id } = useParams<{ id: string }>(); const [game, setGame] = useState<Game | null>(null); const [newService, setNewService] = useState(emptyService); const [message, setMessage] = useState("");
  const load = () => fetch("/api/admin/games").then((response) => response.ok ? response.json() : []).then((items: Game[]) => { const next = items.find((item) => String(item.id) === id) ?? null; if (next) next.services.sort((a, b) => a.sort_order - b.sort_order || a.id - b.id); setGame(next); });
  useEffect(() => { void load(); }, [id]);
  const updateGame = <K extends keyof Game>(key: K, value: Game[K]) => game && setGame({ ...game, [key]: value });
  const updateService = <K extends keyof Service>(serviceId: number, key: K, value: Service[K]) => game && setGame({ ...game, services: game.services.map((item) => item.id === serviceId ? { ...item, [key]: value } : item) });
  const saveGame = async (event: FormEvent) => { event.preventDefault(); if (!game) return; setMessage("保存中..."); const response = await fetch(`/api/admin/games/${game.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload(game)) }); setMessage(response.ok ? "游戏资料已保存" : "保存失败，请检查 Slug 是否重复"); if (response.ok) void load(); };
  const saveService = async (service: Service) => { setMessage("保存服务中..."); const response = await fetch(`/api/admin/services/${service.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(service) }); setMessage(response.ok ? "服务已保存" : "服务保存失败"); if (response.ok) void load(); };
  const toggleService = async (service: Service) => { await fetch(`/api/admin/services/${service.id}/${service.is_active ? "disable" : "enable"}`, { method: "POST" }); void load(); };
  const moveService = async (index: number, direction: -1 | 1) => { if (!game) return; const target = index + direction; if (target < 0 || target >= game.services.length) return; const next = [...game.services]; [next[index], next[target]] = [next[target], next[index]]; await fetch(`/api/admin/games/${game.id}/services/reorder`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(next.map((item, position) => ({ id: item.id, sort_order: position }))) }); void load(); };
  const addService = async (event: FormEvent) => { event.preventDefault(); if (!game) return; setMessage("添加服务中..."); const response = await fetch(`/api/admin/games/${game.id}/services`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...newService, sort_order: game.services.length }) }); if (response.ok) { setNewService(emptyService); setMessage("服务已添加"); void load(); } else setMessage("添加失败"); };
  const chooseCover = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append("file", file); const response = await fetch("/api/admin/uploads/game-cover", { method: "POST", body }); if (!response.ok) return setMessage("图片上传失败"); updateGame("cover_image", (await response.json()).path); setMessage("图片已上传，保存游戏后生效"); };
  if (!game) return <AdminLayout active="games" crumb="游戏编辑"><p className="admin-v2-loading">正在加载游戏资料…</p></AdminLayout>;
  return <AdminLayout active="games" crumb={`${game.name} · 编辑`}><AdminPageTitle eyebrow="GAME EDITOR" title={game.name} description="游戏资料与服务项目在此处统一维护，保存后会同步到前台。" actions={<a className="admin-v2-secondary" href="/admin/games">返回目录</a>} />
    <form className="admin-v2-panel admin-v2-form-panel" onSubmit={saveGame}><div className="admin-v2-form-grid"><label className="admin-v2-field"><span>游戏名称</span><input value={game.name} onChange={(event) => updateGame("name", event.target.value)} required /></label><label className="admin-v2-field"><span>Slug</span><input value={game.slug} onChange={(event) => updateGame("slug", event.target.value)} required /></label><label className="admin-v2-field"><span>游戏分类</span><input value={game.tag} onChange={(event) => updateGame("tag", event.target.value)} /></label><label className="admin-v2-field"><span>排序值</span><input type="number" value={game.sort_order} onChange={(event) => updateGame("sort_order", Number(event.target.value))} /></label><label className="admin-v2-field is-wide"><span>前台简介</span><textarea value={game.description} onChange={(event) => updateGame("description", event.target.value)} /></label><label className="admin-v2-field"><span>展示状态</span><select value={game.is_active ? "active" : "inactive"} onChange={(event) => updateGame("is_active", event.target.value === "active")}><option value="active">前台展示</option><option value="inactive">暂不展示</option></select></label><label className="admin-v2-field"><span>游戏封面</span><div className="admin-v2-cover"><img src={game.cover_image} alt="游戏封面"/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseCover} /></div></label></div><div className="admin-v2-save-line"><button className="admin-v2-primary">保存游戏资料</button><span className="admin-v2-message">{message}</span></div></form>
    <section style={{ marginTop: 28 }}><AdminPageTitle eyebrow="SERVICES" title="服务项目" description="前台需求区域展示前 3 项，服务弹窗最多展示前 5 项启用服务。" /><div className="admin-v2-service-list">{game.services.map((service, index) => <article className={`admin-v2-service-card ${service.is_active ? "" : "is-disabled"}`} key={service.id}><b className="admin-v2-service-index">{String(index + 1).padStart(2, "0")}</b><div className="admin-v2-service-fields"><label className="admin-v2-field"><span>服务名称</span><input value={service.name} onChange={(event) => updateService(service.id, "name", event.target.value)} /></label><label className="admin-v2-field"><span>价格</span><input value={service.price} onChange={(event) => updateService(service.id, "price", event.target.value)} /></label><label className="admin-v2-field"><span>服务说明</span><textarea value={service.description} onChange={(event) => updateService(service.id, "description", event.target.value)} /></label></div><div className="admin-v2-service-actions"><button type="button" onClick={() => saveService(service)}>保存</button><button type="button" onClick={() => moveService(index, -1)} disabled={index === 0}>上移</button><button type="button" onClick={() => moveService(index, 1)} disabled={index === game.services.length - 1}>下移</button><button type="button" onClick={() => toggleService(service)}>{service.is_active ? "隐藏" : "展示"}</button></div></article>)}</div>
    <form className="admin-v2-add-service" onSubmit={addService}><h2>新增服务</h2><input required placeholder="服务名称" value={newService.name} onChange={(event) => setNewService({ ...newService, name: event.target.value })}/><input required placeholder="价格，例如：¥ 30" value={newService.price} onChange={(event) => setNewService({ ...newService, price: event.target.value })}/><textarea placeholder="服务说明" value={newService.description} onChange={(event) => setNewService({ ...newService, description: event.target.value })}/><div className="admin-v2-save-line"><button className="admin-v2-primary">添加服务</button></div></form></section>
  </AdminLayout>;
}
