"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";

type Service = { id: number; name: string; price: string; description: string; sort_order: number; is_active: boolean };
type Game = { id: number; name: string; slug: string; tag: string; description: string; cover_image: string; sort_order: number; services: Service[] };
const emptyService = { name: "", price: "", description: "", sort_order: 0, is_active: true };

export default function EditGame() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const [game, setGame] = useState<Game | null>(null);
  const [service, setService] = useState(emptyService);
  const [dirty, setDirty] = useState(false);
  const [message, setMessage] = useState("");
  const load = () => fetch("/api/admin/games").then((response) => response.json()).then((games: Game[]) => setGame(games.find((item) => String(item.id) === params.id) ?? null));
  useEffect(() => { void load(); }, [params.id]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  if (!game) return <main className="admin-shell"><section className="dashboard"><h1>Loading...</h1></section></main>;
  const saveGame = async (event: FormEvent) => { event.preventDefault(); setMessage("Saving..."); const response = await fetch(`/api/admin/games/${game.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(game) }); setMessage(response.ok ? "Saved" : "Save failed"); setDirty(!response.ok); };
  const addService = async (event: FormEvent) => { event.preventDefault(); const response = await fetch(`/api/admin/games/${game.id}/services`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(service) }); if (response.ok) { setService(emptyService); void load(); } };
  const toggleService = async (item: Service) => { await fetch(`/api/admin/services/${item.id}/${item.is_active ? "disable" : "enable"}`, { method: "POST" }); void load(); };
  const editService = async (item: Service) => { const name = window.prompt("Service name", item.name); if (name === null) return; const price = window.prompt("Price", item.price); if (price === null) return; const description = window.prompt("Description", item.description); if (description === null) return; await fetch(`/api/admin/services/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, price, description, sort_order: item.sort_order, is_active: item.is_active }) }); void load(); };
  const moveService = async (index: number, direction: -1 | 1) => { const nextIndex = index + direction; if (nextIndex < 0 || nextIndex >= game.services.length) return; const reordered = [...game.services]; [reordered[index], reordered[nextIndex]] = [reordered[nextIndex], reordered[index]]; await fetch(`/api/admin/games/${game.id}/services/reorder`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(reordered.map((item, position) => ({ id: item.id, sort_order: position }))) }); void load(); };
  const chooseCover = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append("file", file); const upload = await fetch("/api/admin/uploads/game-cover", { method: "POST", body }); if (!upload.ok) { setMessage("Cover upload failed"); return; } setGame({ ...game, cover_image: (await upload.json()).path }); setDirty(true); setMessage("Cover uploaded. Save the game to associate it."); };
  return <main className="admin-shell"><nav className="admin-nav"><strong>11 Esports Admin</strong><a href="/admin">Dashboard</a><a href="/admin/games">Games</a><a href="/admin/settings">Settings</a></nav><section className="dashboard"><p className="eyebrow">GAME EDITOR</p><h1>{game.name}</h1><form className="settings-form" onSubmit={saveGame}><label>Name<input value={game.name} onChange={(event) => { setGame({ ...game, name: event.target.value }); setDirty(true); }} /></label><label>Slug<input value={game.slug} onChange={(event) => { setGame({ ...game, slug: event.target.value }); setDirty(true); }} /></label><label>Tag<input value={game.tag} onChange={(event) => { setGame({ ...game, tag: event.target.value }); setDirty(true); }} /></label><label>Description<textarea value={game.description} onChange={(event) => { setGame({ ...game, description: event.target.value }); setDirty(true); }} /></label><label>Order<input type="number" value={game.sort_order} onChange={(event) => { setGame({ ...game, sort_order: Number(event.target.value) }); setDirty(true); }} /></label><label>Cover<input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseCover} /><img className="settings-preview" src={game.cover_image} alt="Game cover" /></label><div><button className="admin-action">Save game</button><span className="save-message">{message}</span></div></form><h2 className="subheading">Services</h2><div className="admin-game-list">{game.services.map((item, index) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.price} · {item.description}</span></div><div><button onClick={() => editService(item)}>Edit</button><button onClick={() => moveService(index, -1)}>Up</button><button onClick={() => moveService(index, 1)}>Down</button><button onClick={() => toggleService(item)}>{item.is_active ? "Disable" : "Enable"}</button></div></article>)}</div><form className="service-add" onSubmit={addService}><h2>Add service</h2><input placeholder="Name" value={service.name} onChange={(event) => setService({ ...service, name: event.target.value })} required /><input placeholder="Price" value={service.price} onChange={(event) => setService({ ...service, price: event.target.value })} required /><input placeholder="Description" value={service.description} onChange={(event) => setService({ ...service, description: event.target.value })} /><button className="admin-action">Add service</button></form><button className="back-link" onClick={() => router.push("/admin/games")}>Back to games</button></section></main>;
}
